services:
  bot:
    image: dvmn-support-bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/src
    env_file:
      - .env
    secrets:
      - google_application_credentials
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/google_application_credentials
    command:
      - "python"
      - "/src/main.py"


secrets:
  google_application_credentials:
    file: ./credentials.json



